### ISSUE TITLE
Running Fails

### ISSUE THREAD

**Issue by BrunoFischerGermany** [i1v/googleplay#2]
Hello!

i clone the repro and i do "go build" without errors

But then i want too execute "./cmd/googleplay/googleplay -email MyEmail@gmail.com -password myPass"

I got this Error message:

`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x4a pc=0x6bd583]`
`goroutine 1 [running]:`
`2a.pages.dev/rosso/tls.(*Client_Hello).UnmarshalText(0xc0000c3c10, {0xc0000e2180?, 0x747e51?, 0xc?})`
`        /home/anwender/go/pkg/mod/2a.pages.dev/rosso@v1.0.8/tls/unmarshal.go:43 +0x8e3`
`2a.pages.dev/googleplay.New_Auth({0x7ffcfd3156b4, 0x25}, {0x7ffcfd3156e4, 0x10})`
`        /home/anwender/googleplay/auth.go:33 +0x43c`
`main.flags.do_auth({{0x0, 0x0}, 0x0, {0x7ffcfd3156b4, 0x25}, {0x7ffcfd3156e4, 0x10}, 0x0, 0x0, 0x0, ...}, ...)`
`        /home/anwender/googleplay/cmd/googleplay/googleplay.go:13 +0x6a`
`main.main()`
`        /home/anwender/googleplay/cmd/googleplay/main.go:51 +0x3c5`

Whats wrong?

Thanks

**Comment by i1v** [comment]
should be fixed now. I wrote some new code for the TLS, but I forgot to instantiate a pointer. you should be able to use current `main`, or I pushed a new tag as well:

https://github.com/i1v/googleplay/blob/affa05955356cb8cd528c0fd3d937ac5c9f15c38/auth.go#L32

**Comment by BrunoFischerGermany** [comment]
Thanks. Its working now.
