### ISSUE TITLE
Is there a way to provide the output filename?

### ISSUE THREAD

**Issue by ahm750** [i1v/googleplay#3]
I want to pass a filename (without extension) in the CLI so that the file is saved using that name. Is this possible?

**Comment by i1v** [comment]
the current options are here:

https://github.com/i1v/googleplay/blob/6f045c74a8b40c33c7beeb2c1a8662930fa7ecc1/cmd/googleplay/main.go#L23-L40

you cannot currently choose an output name. if you wish to do that, you can edit the source code. if you are interested in paid support, my info is here:

https://github.com/i1v/googleplay#contact

**Comment by i1v** [comment]
Its been a day, so I am gonna go ahead and close this. Feel free to comment further if you want to continue the discussion
