### ISSUE TITLE
Choosing device hardware

### ISSUE THREAD

**Issue by DavidRodriguezTorrado** [i1v/googleplay#4]
First of all, great work and great repo!
I've download apps for x86 successfully. But is there any way to change it to download arm apks?
Tried with option `-p 2`, but no arm.bin file is being created, only the x86.bin file. I tried also with -device {GSFID} but I haven't been lucky either.
It would be very helpful if someone could clarify how to configure it for Android 11 arm devices.
Again, great Work Steven!

**Comment by i1v** [comment]
please provide example app

**Comment by DavidRodriguezTorrado** [comment]
Thank you for your answer!
For example, I would like to download the apk: com.cuseum.memorialUnionGallery for arm64 devices running Android 11.
